
version: "2"

run:
  timeout: 5m
  concurrency: 0
  tests: true
  modules-download-mode: readonly
  relative-path-mode: cfg

linters:
  default: none
  enable:
    - revive
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - bodyclose
    - noctx
    - errorlint
    - gocritic
  settings:
    govet:
      enable:
        - shadow

  exclusions:
    generated: strict
    paths:
      - vendor
      - third_party
      - testdata


issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
