services:
  app:
    build:
      dockerfile: Dockerfile.dev
      args:
        GO_VERSION: ${GO_VERSION}
    ports:
      - "${GO_PORT:-8375}:${GO_PORT:-8375}"
    volumes:
      - .:/app
      - ./tmp/uploads:/var/sanctum/uploads
    command: air -c .air.toml
    env_file:
      - .env

  postgres:
    ports:
      - "5432:5432"
    healthcheck:
      interval: 2s
      timeout: 3s
      retries: 10

  redis:
    ports:
      - "6379:6379"
    healthcheck:
      interval: 2s
      timeout: 3s
      retries: 10

  frontend:
    build:
      dockerfile: Dockerfile.dev
      args:
        BUN_VERSION: ${BUN_VERSION}
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:${GO_PORT:-8375}/api
    volumes:
      - ./frontend:/app
      - ./tmp/uploads:/var/sanctum/uploads:ro

  # Local Media Server for RTMP -> HLS
  media-server:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935" # RTMP OBS Ingest
      - "8082:80"   # HLS Playback
    volumes:
      - ./infra/nginx-rtmp/nginx.conf:/etc/nginx/nginx.conf
      - /tmp/hls:/tmp/hls # Shared volume for segments (internal)

  # Test services (start with: docker compose --profile test up)
  postgres_test:
    profiles:
      - test
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: sanctum_test
      POSTGRES_USER: sanctum_user
      POSTGRES_PASSWORD: sanctum_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sanctum_user -d sanctum_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-test:
    profiles:
      - test
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        GO_VERSION: ${GO_VERSION}
    depends_on:
      redis:
        condition: service_healthy
      postgres_test:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres_test
      - DB_PORT=5432
      - DB_USER=sanctum_user
      - DB_PASSWORD=sanctum_password
      - DB_NAME=sanctum_test
      - REDIS_URL=redis:6379
      - GIN_MODE=release
      - APP_ENV=testing

volumes:
  postgres_test_data:
