services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY:-cburns/sanctum}/backend:latest
    environment:
      - APP_ENV=production
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/config.production.yml:/config.production.yml:ro
      - /mnt/storage/Sanctum/prod/uploads:/var/sanctum/uploads
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 768M
        reservations:
          memory: 128M

  postgres:
    restart: always
    volumes:
      - /mnt/storage/Sanctum/prod/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 1G
        reservations:
          memory: 256M

  redis:
    restart: always
    volumes:
      - /mnt/storage/Sanctum/prod/redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          memory: 64M

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-cburns/sanctum}/frontend:latest
    ports:
      - "80:80"
    volumes:
      - /mnt/storage/Sanctum/prod/uploads:/var/sanctum/uploads:ro
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          memory: 32M
