services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        GO_VERSION: ${GO_VERSION}
    ports:
      - "${GO_PORT:-8375}:${GO_PORT:-8375}"
    volumes:
      - .:/app
    command: air -c .air.toml
    environment:
      - REDIS_URL=redis:6379
      - DB_HOST=postgres
      - APP_ENV=${APP_ENV:-development}

  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      interval: 2s
      timeout: 3s
      retries: 10

  redis:
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    healthcheck:
      interval: 2s
      timeout: 3s
      retries: 10

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
      args:
        BUN_VERSION: ${BUN_VERSION}
    ports:
      - "${VITE_PORT:-5173}:5173"
    environment:
      - VITE_API_URL=http://localhost:8375/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Local Media Server for RTMP -> HLS
  media-server:
    image: tiangolo/nginx-rtmp
    ports:
      - "${RTMP_PORT:-1935}:1935" # RTMP OBS Ingest
      - "${HLS_PORT:-8082}:80"   # HLS Playback
    volumes:
      - ./infra/nginx-rtmp/nginx.conf:/etc/nginx/nginx.conf
      - /tmp/hls:/tmp/hls # Shared volume for segments (internal)

  # Test services (start with: docker compose --profile test up)
  postgres_test:
    profiles:
      - test
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sanctum_test}
      POSTGRES_USER: ${POSTGRES_USER:-sanctum_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-sanctum_password}
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sanctum_user} -d ${POSTGRES_DB:-sanctum_test}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-test:
    profiles:
      - test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        GO_VERSION: ${GO_VERSION}
    depends_on:
      redis:
        condition: service_healthy
      postgres_test:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres_test
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER:-sanctum_user}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-sanctum_password}
      - DB_NAME=${POSTGRES_DB:-sanctum_test}
      - REDIS_URL=redis:6379
      - GIN_MODE=release
      - APP_ENV=testing

volumes:
  postgres_test_data:
