services:
  app:
    image: ghcr.io/${GITHUB_REPOSITORY:-cburns/sanctum}/backend:latest
    environment:
      - APP_ENV=staging
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend/config.staging.yml:/config.staging.yml:ro
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          memory: 128M

  postgres:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
        reservations:
          memory: 128M

  redis:
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          memory: 32M

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-cburns/sanctum}/frontend:latest
    ports:
      - "8081:80"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          memory: 32M
