services:
  gateway:
    image: nginx:1.27-alpine
    container_name: sanctum_gateway
    ports:
      - "8080:80"
    volumes:
      - ./infra/nginx/gateway.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - frontend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
