services:
  app:
    environment:
      - DB_HOST=postgres_test
      - DB_NAME=${POSTGRES_DB:-sanctum_test}
      - DB_USER=${POSTGRES_USER:-sanctum_user}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-sanctum_password}
      - POSTGRES_USER=${POSTGRES_USER:-sanctum_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sanctum_password}
      - POSTGRES_DB=${POSTGRES_DB:-sanctum_test}
  postgres_test:
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-sanctum_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sanctum_password}
      - POSTGRES_DB=${POSTGRES_DB:-sanctum_test}

  redis:
    ports:
      - "${REDIS_E2E_PORT:-6380}:6379"

  playwright:
    build:
      context: .
      dockerfile: frontend/Dockerfile.e2e
    environment:
      - PLAYWRIGHT_BASE_URL=http://frontend:5173
      - PLAYWRIGHT_API_URL=http://app:8375/api
      - PGHOST=postgres_test
      - PGPORT=5432
      - PGUSER=${POSTGRES_USER:-sanctum_user}
      - PGPASSWORD=${POSTGRES_PASSWORD:-sanctum_password}
      - PGDATABASE=${POSTGRES_DB:-sanctum_test}
    depends_on:
      - frontend
      - app
    volumes:
      - ./frontend/reports:/app/reports
    command: ["npx", "playwright", "test", "--project=chromium"]
