ARG GO_VERSION=1.26.0-alpine3.23
FROM golang:${GO_VERSION}

WORKDIR /app/backend

RUN apk add --no-cache build-base libwebp-dev

# Install air for hot reloading
RUN go install github.com/air-verse/air@latest

# Copy go mod files
COPY backend/go.mod backend/go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY backend/ .

ENV PORT=8375
EXPOSE 8375

CMD ["air", "-c", ".air.toml"]
