FROM golang:1.25-alpine

WORKDIR /app

# Install air for hot reloading
RUN go install github.com/air-verse/air@latest

# Copy go mod files
COPY go.mod ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

ENV PORT=8080
EXPOSE 8080

CMD ["air", "-c", ".air.toml"]