name: 🚀 Feature Request
description: Suggest an idea for Sanctum
title: "[FEAT]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea for a new feature? Tell us about it!
  - type: textarea
    id: description
    attributes:
      label: What is the feature?
      description: A clear and concise description of what the feature is.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternatives considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
